
ppm2:
  stage: build
  when: always
  script:
    - rm -rf ./lua
    - mkdir lua
    - sh build.sh
  artifacts:
    paths:
      - lua/*

test:moonlint:
  script:
    - moonc -l moon/*

linter:
  dependencies:
    - ppm2
  script:
    - sh luacheck.sh
